// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBU0pY53wn1dwvD5D4zxPjnned0Svup-I',
    appId: '1:1088238810296:web:b99d7e6be9dc556745b04d',
    messagingSenderId: '1088238810296',
    projectId: 'flattr-76467',
    authDomain: 'flattr-76467.firebaseapp.com',
    storageBucket: 'flattr-76467.appspot.com',
    measurementId: 'G-453B0SZQNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtfa5bab_5Nudv_XtJdOICEtneVUGlYc8',
    appId: '1:1088238810296:android:25cb079f12815a2045b04d',
    messagingSenderId: '1088238810296',
    projectId: 'flattr-76467',
    storageBucket: 'flattr-76467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYhhNlRL22iEE5ImtAZzi4nJWpOLmU1nI',
    appId: '1:1088238810296:ios:e8efd152e06583d545b04d',
    messagingSenderId: '1088238810296',
    projectId: 'flattr-76467',
    storageBucket: 'flattr-76467.appspot.com',
    iosBundleId: 'com.example.pilotWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYhhNlRL22iEE5ImtAZzi4nJWpOLmU1nI',
    appId: '1:1088238810296:ios:444c8d72a6d9693c45b04d',
    messagingSenderId: '1088238810296',
    projectId: 'flattr-76467',
    storageBucket: 'flattr-76467.appspot.com',
    iosBundleId: 'com.example.pilotWebApp.RunnerTests',
  );
}
